import { StyleSheet } from 'react-native';
import { colors } from './colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
    padding: 20,
  },
  center: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  title: {
    fontSize: 22,
    fontWeight: 'bold',
    color: colors.primary,
    marginBottom: 15,
  },
  headingLarge: {
    fontSize: 28,
    fontWeight: '800',
    color: colors.text,
    marginBottom: 12,
  },
  sectionHeader: {
    fontSize: 18,
    fontWeight: '800',
    color: colors.text,
    marginTop: 18,
    marginBottom: 10,
  },
  card: {
    backgroundColor: colors.white,
    padding: 15,
    marginBottom: 10,
    borderRadius: 8,
    elevation: 2,
  },
  cardTurno: {
    backgroundColor: colors.white,
    padding: 14,
    marginBottom: 12,
    borderRadius: 14,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
  },
  turnoRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  numeroCircle: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#e6fbef',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  numeroText: {
    color: '#0b8546',
    fontWeight: '800',
  },
  tramiteTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: colors.text,
  },
  tramiteSubtitle: {
    color: '#6b6b6b',
    marginTop: 4,
  },
  statusPill: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 16,
    alignSelf: 'flex-start',
    marginTop: 8,
  },
  statusText: {
    fontSize: 12,
    fontWeight: '700',
  },
  actionsRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginTop: 12,
  },
  actionText: {
    marginLeft: 12,
    color: colors.primary,
    fontWeight: '700',
  },
  cardCentered: {
    backgroundColor: colors.white,
    padding: 24,
    borderRadius: 12,
    elevation: 4,
    width: '92%',
    alignSelf: 'center',
  },
  heroBackground: {
    flex: 1,
    backgroundColor: '#0c28b4',
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    height: 48,
    paddingHorizontal: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e6e6e6',
    marginVertical: 8,
  },
  inputIcon: {
    marginRight: 10,
    color: '#8a8a8a',
    fontSize: 18,
    width: 22,
    textAlign: 'center',
  },
  secondaryButtonGreen: {
    backgroundColor: colors.secondary,
    paddingVertical: 12,
    borderRadius: 22,
    alignItems: 'center',
    marginTop: 8,
    width: '100%',
  },
  secondaryButtonText: {
    color: colors.white,
    fontWeight: '700',
  },
  dashboardTile: {
    backgroundColor: '#eef6ff',
    padding: 16,
    borderRadius: 12,
    elevation: 3,
    alignItems: 'center',
    justifyContent: 'center',
    width: '48%',
    minHeight: 100,
    marginBottom: 12,
  },
  input: {
    backgroundColor: '#fff',
    height: 48,
    paddingHorizontal: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e6e6e6',
    marginVertical: 8,
    fontSize: 16,
  },
  primaryButton: {
    backgroundColor: colors.primary,
    paddingVertical: 14,
    borderRadius: 10,
    alignItems: 'center',
    width: '100%',
  },
  primaryButtonText: {
    color: colors.white,
    fontWeight: '700',
  },
  chip: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#e6e6e6',
    backgroundColor: '#fff',
    marginRight: 8,
    marginBottom: 8,
  },
  chipSelected: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  chipTextSelected: {
    color: '#fff',
    fontWeight: '700',
  },
  disabledButton: {
    backgroundColor: '#f1f3f5',
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  changeTramiteButton: {
    backgroundColor: colors.secondary,
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'center',
    padding: 20,
  },
  modalContent: {
    backgroundColor: colors.white,
    borderRadius: 12,
    maxHeight: '80%',
    padding: 0,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: colors.primary,
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
  },
  modalHeaderTitle: {
    color: colors.white,
    fontSize: 18,
    fontWeight: '800',
  },
  modalClose: {
    color: colors.white,
    fontWeight: '700',
  },
  tramitesItem: {
    backgroundColor: '#f6f9ff',
    padding: 14,
    borderRadius: 12,
    marginRight: 12,
    minWidth: 160,
    elevation: 2,
  },
  tramitesItemText: {
    fontWeight: '800',
    color: colors.primary,
  },
  text: {
    color: colors.text,
  },
  // Home screen
  heroCard: {
    backgroundColor: colors.primary,
    borderRadius: 14,
    padding: 18,
    marginBottom: 16,
    elevation: 3,
  },
  heroTitle: {
    color: '#fff',
    fontSize: 20,
    fontWeight: '800',
    marginBottom: 6,
  },
  heroSubtitle: {
    color: '#dfe9ff',
    fontSize: 14,
  },
  quickActionsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    alignItems: 'flex-start',
  },
  tileIcon: {
    width: 44,
    height: 44,
    borderRadius: 10,
    backgroundColor: '#81b3c0',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  upcomingCard: {
    backgroundColor: colors.white,
    padding: 14,
    borderRadius: 12,
    elevation: 2,
    marginBottom: 12,
  },
  // Profile
  profileAvatar: {
    width: 96,
    height: 96,
    borderRadius: 48,
    backgroundColor: '#eef4ff',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  profileName: {
    fontSize: 20,
    fontWeight: '800',
    marginBottom: 6,
  },
  profileCard: {
    backgroundColor: colors.white,
    padding: 18,
    borderRadius: 12,
    elevation: 3,
    marginBottom: 12,
  },
  profileInfoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f3f5',
  },
  profileInfoLabel: {
    fontWeight: '700',
    color: '#333',
  },
  profileInfoValue: {
    color: '#666',
  },
  profileField: {
    width: '100%',
    backgroundColor: '#fff',
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e6e6e6',
    marginBottom: 10,
  },
  profileActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 12,
  },
  profileButton: {
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 120,
  },
  profileButtonPrimary: {
    backgroundColor: colors.primary,
  },
  profileButtonSecondary: {
    backgroundColor: colors.secondary,
  },
  profileButtonText: {
    color: colors.white,
    fontWeight: '700',
  },
  profileIcon: {
    marginRight: 8,
  },
  // Header
  headerBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 18,
    paddingBottom: 12,
    backgroundColor: colors.primary,
  },
  headerGreeting: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '800',
  },
  headerIcons: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  iconButton: {
    marginLeft: 12,
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  badge: {
    position: 'absolute',
    top: 6,
    right: 6,
    backgroundColor: '#dc3545',
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 4,
  },
  badgeText: {
    color: '#fff',
    fontSize: 11,
    fontWeight: '700',
  },
});
